### ISSUE TITLE
Pydantic related TypeError when importing DIMR 

### ISSUE THREAD

**Issue by LisaWeijers** [Deltares/HYDROLIB-core#204]
**Describe the bug**
I'm not sure since when this bug occurs, but I can no longer import DIMR. I have reinstalled hydrolib core in a fresh, new environment and the issue persists. A colleague encountered the same issue. 

**To Reproduce**
```
from hydrolib.core.io.dimr.models import DIMR
help(DIMR)
```
Console output: 
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\envs\hydrolib_env\lib\site-packages\hydrolib\core\io\dimr\models.py", line 273, in <module>
    class DIMR(FileModel):
  File "pydantic\main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 603, in pydantic.fields.ModelField._type_analysis
TypeError: `discriminator` can only be used with `Union` type
python-BaseException
```

**Expected behavior**
I expected that this would import the DIMR from `from hydrolib.core.io.dimr.models`

Interestingly enough this does still work:
```
>>> import hydrolib.core.io.dimr as d
>>> help(d)
Help on package hydrolib.core.io.dimr in hydrolib.core.io:
NAME
    hydrolib.core.io.dimr
PACKAGE CONTENTS
    models
    parser
    serializer
FILE
    (built-in)
```
but as soon as I go into the models part, it has issues.

**Screenshots**

**Version info (please complete the following information):**
 - OS: Windows 10
 - Python 3.8
 - Hydrolib-core 0.2.0
 - pydantic 1.9.0 
 (I thought maybe it does some dependancy wrong with pydantic? so I listed pydantic's version too)

**Additional context**

**Comment by arthurvd** [comment]
This is occurring since pydantic==1.9.0
Probably related to this bugreport: https://github.com/samuelcolvin/pydantic/issues/3694

Behavior with pydantic==1.8.2 is correct.

**Comment by LisaWeijers** [comment]
downgraded to pydantic==1.8.2 worked.

Since pydantic gets installed as a dependency when installing hydrolib-core, it would be nice to keep an 1.8.2 (or 1.8.x?) as a dependancy. the toml now defines this dependency:
```pydantic = {extras = ["dotenv"], version = "^1.8"}```

So perhaps change that to 
```pydantic = {extras = ["dotenv"], version = "^1.8.0"}```
so it sticks to 1.8.x but picks the highest available version? 

Or just pin it as 1.8.2.
