### ISSUE TITLE
Support D-Water Quality input in ExtOldModel

### ISSUE THREAD

**Issue by SCLaan** [Deltares/HYDROLIB-core#551]
**Is your feature request related to a problem? Please describe.**
At present when loading the old format ext file of a coupled D-Flow FM and D-Water Quality model multiple validation errors occur, because the water quality input is not yet supported.

**Describe the solution you'd like**
I would like to see support for water quality input in ExtOldModel. These errors occur for the following input under QUANTITY:
- waqfunctionXXX (with a user specified function, e.g. waqfunctionRadSurf, waqfunctionVWind)
- waqmassbalanceareaXXX (with a user specified domain name)
- waqparameterXXX (with a user specified parameter name)
- tracerbndXXX (in combination with FILETYPE=9)
- initialtracerXXX (in combination with FILETYPE=10)
- initialwaqbotXXX (in combination with FILETYPE=10)

**Additional context**
The following model contains such parameters:
```python
import hydrolib.core.dflowfm as hcdfm
ext_file = r'p:\archivedprojects\11208983-epd-support-tools\training\HK-DFM_June2023\HK-DFM_Day3_WaterQuality\Demo_Model_Input\HK-FM_bnd.ext'
ext_data = hcdfm.ExtOldModel(ext_file, recurse=False)
```

At the moment, it raises the following error:
```
Traceback (most recent call last):
  File "C:\DATA\checkouts\hydromt_delft3dfm\.pixi\envs\default\Lib\site-packages\IPython\core\interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-454cace44ba4>", line 3, in <module>
    ext_data = hcdfm.ExtOldModel(ext_file, recurse=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DATA\checkouts\hydromt_delft3dfm\.pixi\envs\default\Lib\site-packages\hydrolib\core\base\models.py", line 415, in __init__
    super().__init__(*args, **kwargs)
  File "C:\DATA\checkouts\hydromt_delft3dfm\.pixi\envs\default\Lib\site-packages\hydrolib\core\base\models.py", line 103, in __init__
    raise ValidationError.from_exception_data(
pydantic_core._pydantic_core.ValidationError: 77 validation errors for ExtOldModel
`HK-FM_bnd.ext`.forcing.71.QUANTITY
  Value error, QUANTITY 'waqmassbalanceareaDomain' not supported. Supported values: 1d2dbnd, absgenbnd, criticaloutflowbnd, dischargebnd, neumannbnd, normalvelocitybnd, outflowbnd, qhbnd, qhubnd, riemannbnd, salinitybnd, sedimentbnd, tangentialvelocitybnd, temperaturebnd, uxuyadvectionvelocitybnd, velocitybnd, waterlevelbnd, waveenergybnd, weiroutflowbnd, airdensity, airpressure, airpressure_stressx_stressy, airpressure_windx_windy, airpressure_windx_windy_charnock, airtemperature, atmosphericpressure, charnock, cloudiness, dewpoint, dewpoint_airtemperature_cloudiness, dewpoint_airtemperature_cloudiness_solarradiation, humidity, humidity_airtemperature_cloudiness, humidity_airtemperature_cloudiness_solarradiation, longwaveradiation, rainfall, rainfall_rate, solarradiation, netsolarradiation, stressx, stressxy, stressy, windx, windy, windxy, solarradiationfactor, windspeedfactor, windstresscoefficient, wind_speed, wind_from_direction, advectiontype, bedrock_surface_elevation, friction_coefficient_time_dependent, frictioncoefficient, frictiontrtfactor, horizontaleddydiffusivitycoefficient, horizontaleddyviscositycoefficient, ibedlevtype, infiltrationcapacity, interceptionlayerthickness, internaltidesfrictioncoefficient, linearfrictioncoefficient, nudge_salinity_temperature, nudgerate, nudgetime, sea_ice_area_fraction, sea_ice_thickness, secchidepth, stemdensity, stemdiameter, stemheight, wavesignificantheight, waveperiod, wavedirection, wavebreakerdissipation, whitecappingdissipation, xwaveforce, ywaveforce, totalwaveenergydissipation, ibotlevtype, floe_diameter, waqparameter, initialsalinity, initialsalinitybot, initialsalinitytop, initialtemperature, initialunsaturatedzonethickness, initialvelocity, initialvelocityx, initialvelocityy, initialverticalsalinityprofile, initialverticaltemperatureprofile, initialwaterlevel, bedlevel, bedlevel1d, bedlevel2d, initialwaterlevel1d, initialwaterlevel2d, discharge_salinity_temperature_sorsin, damlevel, gateloweredgelevel, generalstructure, pump, pump1d, valve1d, shiptxy, movingstationxy, lateraldischarge, lateraldischarge1d, lateraldischarge2d [type=value_error, input_value='waqmassbalanceareaDomain', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/value_error
`HK-FM_bnd.ext`.forcing.72.QUANTITY
  Value error, QUANTITY 'waqmassbalanceareaHongKong' not supported. Supported values: 1d2dbnd, absgenbnd, criticaloutflowbnd, dischargebnd, neumannbnd, normalvelocitybnd, outflowbnd, qhbnd, qhubnd, riemannbnd, salinitybnd, sedimentbnd, tangentialvelocitybnd, temperaturebnd, uxuyadvectionvelocitybnd, velocitybnd, waterlevelbnd, waveenergybnd, weiroutflowbnd, airdensity, airpressure, airpressure_stressx_stressy, airpressure_windx_windy, airpressure_windx_windy_charnock, airtemperature, atmosphericpressure, charnock, cloudiness, dewpoint, dewpoint_airtemperature_cloudiness, dewpoint_airtemperature_cloudiness_solarradiation, humidity, humidity_airtemperature_cloudiness, humidity_airtemperature_cloudiness_solarradiation, longwaveradiation, rainfall, rainfall_rate, solarradiation, netsolarradiation, stressx, stressxy, stressy, windx, windy, windxy, solarradiationfactor, windspeedfactor, windstresscoefficient, wind_speed, wind_from_direction, advectiontype, bedrock_surface_elevation, friction_coefficient_time_dependent, frictioncoefficient, frictiontrtfactor, horizontaleddydiffusivitycoefficient, horizontaleddyviscositycoefficient, ibedlevtype, infiltrationcapacity, interceptionlayerthickness, internaltidesfrictioncoefficient, linearfrictioncoefficient, nudge_salinity_temperature, nudgerate, nudgetime, sea_ice_area_fraction, sea_ice_thickness, secchidepth, stemdensity, stemdiameter, stemheight, wavesignificantheight, waveperiod, wavedirection, wavebreakerdissipation, whitecappingdissipation, xwaveforce, ywaveforce, totalwaveenergydissipation, ibotlevtype, floe_diameter, waqparameter, initialsalinity, initialsalinitybot, initialsalinitytop, initialtemperature, initialunsaturatedzonethickness, initialvelocity, initialvelocityx, initialvelocityy, initialverticalsalinityprofile, initialverticaltemperatureprofile, initialwaterlevel, bedlevel, bedlevel1d, bedlevel2d, initialwaterlevel1d, initialwaterlevel2d, discharge_salinity_temperature_sorsin, damlevel, gateloweredgelevel, generalstructure, pump, pump1d, valve1d, shiptxy, movingstationxy, lateraldischarge, lateraldischarge1d, lateraldischarge2d [type=value_error, input_value='waqmassbalanceareaHongKong', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/value_error
`HK-FM_bnd.ext`.forcing.73.QUANTITY
  Value error, QUANTITY 'waqmassbalanceareaNoProcessArea' not supported. Supported values: 1d2dbnd, absgenbnd, criticaloutflowbnd, dischargebnd, neumannbnd, normalvelocitybnd, outflowbnd, qhbnd, qhubnd, riemannbnd, salinitybnd, sedimentbnd, tangentialvelocitybnd, temperaturebnd, uxuyadvectionvelocitybnd, velocitybnd, waterlevelbnd, waveenergybnd, weiroutflowbnd, airdensity, airpressure, airpressure_stressx_stressy, airpressure_windx_windy, airpressure_windx_windy_charnock, airtemperature, atmosphericpressure, charnock, cloudiness, dewpoint, dewpoint_airtemperature_cloudiness, dewpoint_airtemperature_cloudiness_solarradiation, humidity, humidity_airtemperature_cloudiness, humidity_airtemperature_cloudiness_solarradiation, longwaveradiation, rainfall, rainfall_rate, solarradiation, netsolarradiation, stressx, stressxy, stressy, windx, windy, windxy, solarradiationfactor, windspeedfactor, windstresscoefficient, wind_speed, wind_from_direction, advectiontype, bedrock_surface_elevation, friction_coefficient_time_dependent, frictioncoefficient, frictiontrtfactor, horizontaleddydiffusivitycoefficient, horizontaleddyviscositycoefficient, ibedlevtype, infiltrationcapacity, interceptionlayerthickness, internaltidesfrictioncoefficient, linearfrictioncoefficient, nudge_salinity_temperature, nudgerate, nudgetime, sea_ice_area_fraction, sea_ice_thickness, secchidepth, stemdensity, stemdiameter, stemheight, wavesignificantheight, waveperiod, wavedirection, wavebreakerdissipation, whitecappingdissipation, xwaveforce, ywaveforce, totalwaveenergydissipation, ibotlevtype, floe_diameter, waqparameter, initialsalinity, initialsalinitybot, initialsalinitytop, initialtemperature, initialunsaturatedzonethickness, initialvelocity, initialvelocityx, initialvelocityy, initialverticalsalinityprofile, initialverticaltemperatureprofile, initialwaterlevel, bedlevel, bedlevel1d, bedlevel2d, initialwaterlevel1d, initialwaterlevel2d, discharge_salinity_temperature_sorsin, damlevel, gateloweredgelevel, generalstructure, pump, pump1d, valve1d, shiptxy, movingstationxy, lateraldischarge, lateraldischarge1d, lateraldischarge2d [type=value_error, input_value='waqmassbalanceareaNoProcessArea', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/value_error
`HK-FM_bnd.ext`.forcing.74.QUANTITY
  Value error, QUANTITY 'waqparameterProcessesInactive' not supported. Supported values: 1d2dbnd, absgenbnd, criticaloutflowbnd, dischargebnd, neumannbnd, normalvelocitybnd, outflowbnd, qhbnd, qhubnd, riemannbnd, salinitybnd, sedimentbnd, tangentialvelocitybnd, temperaturebnd, uxuyadvectionvelocitybnd, velocitybnd, waterlevelbnd, waveenergybnd, weiroutflowbnd, airdensity, airpressure, airpressure_stressx_stressy, airpressure_windx_windy, airpressure_windx_windy_charnock, airtemperature, atmosphericpressure, charnock, cloudiness, dewpoint, dewpoint_airtemperature_cloudiness, dewpoint_airtemperature_cloudiness_solarradiation, humidity, humidity_airtemperature_cloudiness, humidity_airtemperature_cloudiness_solarradiation, longwaveradiation, rainfall, rainfall_rate, solarradiation, netsolarradiation, stressx, stressxy, stressy, windx, windy, windxy, solarradiationfactor, windspeedfactor, windstresscoefficient, wind_speed, wind_from_direction, advectiontype, bedrock_surface_elevation, friction_coefficient_time_dependent, frictioncoefficient, frictiontrtfactor, horizontaleddydiffusivitycoefficient, horizontaleddyviscositycoefficient, ibedlevtype, infiltrationcapacity, interceptionlayerthickness, internaltidesfrictioncoefficient, linearfrictioncoefficient, nudge_salinity_temperature, nudgerate, nudgetime, sea_ice_area_fraction, sea_ice_thickness, secchidepth, stemdensity, stemdiameter, stemheight, wavesignificantheight, waveperiod, wavedirection, wavebreakerdissipation, whitecappingdissipation, xwaveforce, ywaveforce, totalwaveenergydissipation, ibotlevtype, floe_diameter, waqparameter, initialsalinity, initialsalinitybot, initialsalinitytop, initialtemperature, initialunsaturatedzonethickness, initialvelocity, initialvelocityx, initialvelocityy, initialverticalsalinityprofile, initialverticaltemperatureprofile, initialwaterlevel, bedlevel, bedlevel1d, bedlevel2d, initialwaterlevel1d, initialwaterlevel2d, discharge_salinity_temperature_sorsin, damlevel, gateloweredgelevel, generalstructure, pump, pump1d, valve1d, shiptxy, movingstationxy, lateraldischarge, lateraldischarge1d, lateraldischarge2d [type=value_error, input_value='waqparameterProcessesInactive', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/value_error
`HK-FM_bnd.ext`.forcing.102.METHOD
  Input should be 1, 2, 3, 4, 5, 6, 7 or 11 [type=enum, input_value='0', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/enum
`HK-FM_bnd.ext`.forcing.103.METHOD
  Input should be 1, 2, 3, 4, 5, 6, 7 or 11 [type=enum, input_value='0', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/enum
`HK-FM_bnd.ext`.forcing.104.METHOD
  Input should be 1, 2, 3, 4, 5, 6, 7 or 11 [type=enum, input_value='0', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/enum
[...]
`HK-FM_bnd.ext`.forcing.172.METHOD
  Input should be 1, 2, 3, 4, 5, 6, 7 or 11 [type=enum, input_value='0', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/enum
`HK-FM_bnd.ext`.forcing.173.METHOD
  Input should be 1, 2, 3, 4, 5, 6, 7 or 11 [type=enum, input_value='0', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/enum
`HK-FM_bnd.ext`.forcing.174.METHOD
  Input should be 1, 2, 3, 4, 5, 6, 7 or 11 [type=enum, input_value='0', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/enum
```

**Comment by veenstrajelmer** [comment]
updated path: "p:\11208983-epd-support-tools\training\HK-DFM_June2023\HK-DFM_Day3_WaterQuality\Demo_Model_Input\HK-FM_bnd.ext"

**Comment by tim-vd-aardweg** [comment]
Let's discuss the details @veenstrajelmer & @rhutten

**Comment by tim-vd-aardweg** [comment]
Assigned the issue to @rhutten. She will determine if/when we will pick up this issue.

**Comment by veenstrajelmer** [comment]
Due to several efforts to support WAQ models, this model now loads without issues with the main branch of hydrolib-core, and probably also with the latest version (1.4). I have also created https://github.com/Deltares/HYDROLIB-core/issues/1219 to test whether extforce-convert works correctly for this model.
