### ISSUE TITLE
Unclear error message from bc-validation

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/HYDROLIB-core#560]
**Describe the bug**
I received a faulty bc file from a client, which I got working with help from the HYDROLIB-core validation, but the error messages I got can be clearer.

**To Reproduce**
The (simplified) bc-file looks like this:
```
Time-interpolation              = linear
Vertical position type          = percentage from bed
Vertical position               = 3.6, 27.7
Quantity                        = time
Unit                            = seconds since 1994-01-01 00:00:00
Quantity                        = velocitybnd
Unit                            = m/s
verticalPositionIndex           = 1
Quantity                        = velocitybnd
Unit                            = m/s
verticalPositionIndex           = 2
  16858800 -0.005 0.000 
  16869600 -0.003 -0.003
  16880400 0.003 -0.003 
  16891200 0.017 0.011 
  16902000 0.017 0.016 
  16912800 0.002 0.010 
```

The file can be read+validated with HYDROLIB-core with this code:
```
import hydrolib.core.dflowfm as hcdfm
file_bc = 'Velocity3D_west_small.bc'
fm_bc = hcdfm.ForcingModel(file_bc)
```

A clear error message is thrown:
```
ValidationError: 1 validation error for ForcingModel
Velocity3D_west_small.bc -> forcing -> 0 -> west_0001 -> __root__
  vertPositions is not provided (type=value_error)
```
Action: replace `Vertical position` with `vertPositions` and try again. In the [uxuy example bc-file](https://github.com/Deltares/HYDROLIB-core/blob/main/tests/data/input/dflowfm_individual_files/FlowFM_boundaryconditions3d_and_vectors.bc), this quantity is named `Vertical position specification`

Another error message is thrown:
```
ValidationError: 1 validation error for ForcingModel
Velocity3D_west_small.bc -> forcing -> 0 -> west_0001 -> __root__
  Vertical position index should be between 1 and 2, but None was given (type=value_error)
```

After a bit of puzzling, I figured out that `verticalPositionIndex` should be replaced with `vertPositionIndex`. In the [uxuy example bc-file](https://github.com/Deltares/HYDROLIB-core/blob/main/tests/data/input/dflowfm_individual_files/FlowFM_boundaryconditions3d_and_vectors.bc), this quantity is named `Vertical position`. This is confusingly similar to `vertPositions` above.

After replacing, we get this error message:
```
ValidationError: 1 validation error for ForcingModel
Velocity3D_west_small.bc -> forcing -> 0 -> west_0001 -> vertPositions -> 0
  value is not a valid float (type=type_error.float)
```

I figured that the comma's should be removed from the `Vertpositions` value.

**Expected behavior**
A bit clearer error messages, so the user knows what should be changed. Also, the similarity of `vertPositions` and `Vertical position` (which are the indices and the position values) is a bit confusing.

**Version info (please complete the following information):**
 - OS: Windows
 - Version HYDROLIB-core 0.5.2

**Comment by veenstrajelmer** [comment]
The behaviour with hydrolib-core 1.0.1 is different, but can still be made more friendly. To reproduce:
```python
contents = """
Time-interpolation              = linear
Vertical position type          = percentage from bed
Vertical position               = 3.6, 27.7
Quantity                        = time
Unit                            = seconds since 1994-01-01 00:00:00
Quantity                        = velocitybnd
Unit                            = m/s
verticalPositionIndex           = 1
Quantity                        = velocitybnd
Unit                            = m/s
verticalPositionIndex           = 2
  16858800 -0.005 0.000 
  16869600 -0.003 -0.003
  16880400 0.003 -0.003 
  16891200 0.017 0.011 
  16902000 0.017 0.016 
  16912800 0.002 0.010 
"""

import hydrolib.core.dflowfm as hcdfm
file_bc = 'Velocity3D_west_small.bc'
with open(file_bc, "w") as f:
    f.write(contents)
fm_bc = hcdfm.ForcingModel(file_bc)
```

This code runs successfully, but `fm_bc.forcing` is an empty list. This is because `[forcing]` is missing from the first line in the file, but it would be better to raise an error for file contents not being parsed into something (or were they parsed into some other property?)

Updating the file contents, gives a `ValidationError`. To reproduce:
```python
contents = """
[forcing]
Time-interpolation              = linear
Vertical position type          = percentage from bed
Vertical position               = 3.6, 27.7
Quantity                        = time
Unit                            = seconds since 1994-01-01 00:00:00
Quantity                        = velocitybnd
Unit                            = m/s
verticalPositionIndex           = 1
Quantity                        = velocitybnd
Unit                            = m/s
verticalPositionIndex           = 2
  16858800 -0.005 0.000 
  16869600 -0.003 -0.003
  16880400 0.003 -0.003 
  16891200 0.017 0.011 
  16902000 0.017 0.016 
  16912800 0.002 0.010 
"""

import hydrolib.core.dflowfm as hcdfm
file_bc = 'Velocity3D_west_small.bc'
with open(file_bc, "w") as f:
    f.write(contents)
fm_bc = hcdfm.ForcingModel(file_bc)
```

Raises:
```
Traceback (most recent call last):
  File "C:\Users\veenstra\AppData\Local\miniforge3\envs\hydrolib_core_env\Lib\site-packages\IPython\core\interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-6bc8ee5ab390>", line 26, in <module>
    fm_bc = hcdfm.ForcingModel(file_bc)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DATA\checkouts\hydrolib-core\hydrolib\core\base\models.py", line 415, in __init__
    super().__init__(*args, **kwargs)
  File "C:\DATA\checkouts\hydrolib-core\hydrolib\core\base\models.py", line 103, in __init__
    raise ValidationError.from_exception_data(
pydantic_core._pydantic_core.ValidationError: 1 validation error for ForcingModel
`Velocity3D_west_small.bc`.forcing.0
  Unable to extract tag using discriminator 'function' [type=union_tag_not_found, input_value={'_header': 'forcing', 'd...itionindex': ['1', '2']}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/union_tag_not_found
```

Todo:
- raise error if not all contents are parsed in case of missing forcing block/header
- give a clearer error message
