### ISSUE TITLE
Writing a DIMR model fails (or takes a very long time) when the number of laterals is large

### ISSUE THREAD

**Issue by RuudHurkmans** [Deltares/HYDROLIB-core#722]
**Describe the bug**
When a large set of laterals is added to an ExtModel, DIMR.save() iterates over the laterals, writing the entire .BC file for every lateral. 

[testdata_laterals.zip](https://github.com/user-attachments/files/18163191/testdata_laterals.zip)

**To Reproduce**
- Run the attached script, which reads data from the also attached GPKG. The Hydrolib is needed. 
- it builds a dflowfm-model from branches and laterals. 
- The script gets stuck on the 'dimr.save()' line because it writes the .bc file over and over again.

A workaround is to add only the first lateral to the ExtModel, and then write the other laterals afterwards to the existing .ext-file.

**Expected behavior**
I would expect dimr to write the .ext and .bc file once.

**Version info (please complete the following information):**
 - OS: Windows 11
 - Hydrolib 0.3.1, Hydrolib-core 0.8.0

**Additional context**

**Comment by arthurvd** [comment]
Thanks Ruud, clear explanation, we'll try and look into it.

**Comment by rhutten** [comment]
@MAfarrag, could we pick this issue up for the 1.1 release? Partner are creating workarround to overcome this problem.

**Comment by veenstrajelmer** [comment]
Let's indeed see whether the updating HYDROLIB to HYDROLIB-core v1 (https://github.com/Deltares/HYDROLIB/pull/213) fixes this issue.

**Comment by MAfarrag** [comment]
- Check the source of the issue  
- before doing any work discuss first the priority

**Comment by veenstrajelmer** [comment]
@RuudHurkmans @guydup when running the code from the zipfile with the gpkg from the zipfile, I get the following error when calling `models = Df2HydrolibModel(hydamo)` when running it with the hydrolib-core main branch:
```
Traceback (most recent call last):
  File "C:\Users\veenstra\AppData\Local\miniforge3\envs\hydrolib_env\Lib\site-packages\hydrolib\core\base\models.py", line 80, in __init__
    super().__init__(**data)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\veenstra\AppData\Local\miniforge3\envs\hydrolib_env\Lib\site-packages\pydantic\main.py", line 263, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Constant
datablock
  Value error, NaN is not supported in datablocks. [type=value_error, input_value=[[nan]], input_type=list]
    For further information visit https://errors.pydantic.dev/2.13/v/value_error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\veenstra\AppData\Roaming\JetBrains\PyCharm2026.1\scratches\scratch_14.py", line 62, in <module>
    models = Df2HydrolibModel(hydamo)
  File "C:\DATA\checkouts\hydrolib\hydrolib\dhydamo\converters\df2hydrolibmodel.py", line 64, in __init__
    self.write_all()
    ~~~~~~~~~~~~~~^^
  File "C:\DATA\checkouts\hydrolib\hydrolib\dhydamo\converters\df2hydrolibmodel.py", line 79, in write_all
    self.laterals_to_dhydro()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\DATA\checkouts\hydrolib\hydrolib\dhydamo\converters\df2hydrolibmodel.py", line 314, in laterals_to_dhydro
    lat_bc = Constant(
        name=key,
    ...<3 lines>...
        datablock=[[lateral["discharge"]]],
    )
  File "C:\Users\veenstra\AppData\Local\miniforge3\envs\hydrolib_env\Lib\site-packages\hydrolib\core\base\models.py", line 103, in __init__
    raise ValidationError.from_exception_data(
        title=title, line_errors=errors
    )
pydantic_core._pydantic_core.ValidationError: 1 validation error for Constant
lat_ZL16_929.datablock
  Value error, NaN is not supported in datablocks. [type=value_error, input_value=[[nan]], input_type=list]
    For further information visit https://errors.pydantic.dev/2.13/v/value_error
```

Nans are not allowed in the datablock anymore since https://github.com/Deltares/HYDROLIB-core/issues/433 was fixed. Therefore, it is currently not possible to reproduce the performance lag. Would it be possible to provide another example that shows the problem you are encountering?

**Comment by RuudHurkmans** [comment]
Hi,

Apologies for the belated reply. The file below contains again an isolated example where many laterals from a GPKG are converted to an ExtModel, added to a DIMR-model and then saved (dimr.save()). The last step takes very long (if it succeeds at all) because for every lateral, the entire BC-file is written. 

Change wrt the last version: added a line to take out the NaN-values that blocked conversion to ExtModel. 

[testdata_laterals.zip](https://github.com/user-attachments/files/32474677/testdata_laterals.zip)](testdata_laterals.zip)

Current workaround is to add 1 lateral the ExtModel and then later amend the .ext-file. The text below specifies the issue and suggests a fix:

Description:

When a FileModel (e.g. a ForcingModel backing a .bc file) is referenced multiple times in a model tree — which happens routinely, since FileModel.__new__ (hydrolib/core/base/models.py, ~L318-331) explicitly caches and reuses instances by resolved filepath via a WeakValueDictionary — calling save(recurse=True) on the root model (e.g. DIMR.save()) re-serializes that shared instance once per reference, not once total.

Root cause

ModelTreeTraverser.traverse() (hydrolib/core/base/models.py) walks every pydantic field of every list element with no identity-based deduplication:

def traverse(self, model: BaseModel, acc: TAcc) -> TAcc:
   ```
    for _, value in model:
        if not isinstance(value, list):
            value = [value]
        for v in value:
            if self._should_traverse(v, acc):
                acc = self.traverse(v, acc)
   ```

FileModel._save_tree()'s save_post closure then calls model._save(save_settings) for every FileModel node the traverser visits:

def save_post(model: BaseModel, acc: FileLoadContext) -> FileLoadContext:
    if isinstance(model, FileModel):
        acc.pop_last_parent()
        model._absolute_anchor_path = acc.get_current_parent()
        model._save(save_settings)   # <-- no check whether this instance was already saved
    return acc

Impact

In dflowfm/ext/models.py, Boundary.forcingfile, Meteo.forcingfile, Lateral/SourceSink forcing fields are all ForcingModel references. A realistic ExtModel with N boundary/lateral/meteo blocks sharing one .bc file containing M forcing quantities triggers N full serializations of that M-quantity file on DIMR.save(recurse=True) — i.e. O(N×M) work instead of O(M). For models with hundreds of boundaries sharing one large .bc file, this makes save() extremely slow.

Note: synchronize_filepaths() uses the same unguarded traversal pattern (sync_post), but there the repeated work is cheap (just resetting _absolute_anchor_path), so it's not a performance issue there — flagging for awareness only.

**Suggested fix**

Add an identity-based visited: Set[int] guard to the save traversal, so each unique FileModel instance is serialized at most once regardless of how many parents reference it:

def _save_tree(self, context: FileLoadContext, save_settings: ModelSaveSettings) -> None:
    ...
    visited: Set[int] = set()

    def save_post(model: BaseModel, acc: FileLoadContext) -> FileLoadContext:
        if isinstance(model, FileModel):
            acc.pop_last_parent()
            model._absolute_anchor_path = acc.get_current_parent()
            if id(model) not in visited:
                visited.add(id(model))
                model._save(save_settings)
        return acc

    save_traverser = ModelTreeTraverser[FileLoadContext](
        should_traverse=_should_traverse,
        should_execute=_should_execute,
        pre_traverse_func=save_pre,
        post_traverse_func=save_post,
    )
    save_traverser.traverse(self, context)

A more general fix would add optional dedup support directly to ModelTreeTraverser itself (e.g. an internal _visited: Set[int] that should_execute/should_traverse can consult), since the same unguarded-revisit pattern also exists in show_tree()/_apply_recurse() and could bite other traversal use cases in the future.

Environment

hydrolib-core version: (1.0.1)
Python version: (3.12)

**Comment by veenstrajelmer** [comment]
Thanks for the updated code/data. It took me a while, but I debugged your code and I think I found something interesting. To speed it up, I limited it to the first ten branches/laterals:
```python
import os
from pathlib import Path
from shapely.geometry import Point

from hydrolib.core.dimr.models import DIMR, FMComponent
from hydrolib.core.dflowfm.ext.models import ExtModel
from hydrolib.core.dflowfm.mdu.models import FMModel

# Importing relevant classes from Hydrolib-dhydamo
from hydrolib.dhydamo.core.hydamo import HyDAMO
from hydrolib.dhydamo.converters.df2hydrolibmodel import Df2HydrolibModel
from hydrolib.dhydamo.geometry import mesh
from hydrolib.dhydamo.io.common import ExtendedGeoDataFrame

# path to the data
data_path = os.path.abspath(r'D:\4390.10\laterals')

# path to write the model
output_path = r'output'

#GPKG name
gpkg_filename = os.path.join(data_path, 'testdata_laterals.gpkg')
gpkg_file = gpkg_filename

hydamo = HyDAMO()

hydamo.branches.read_gpkg_layer(
    gpkg_file,
    layer_name="hydroobject",
    index_col="code")

# read laterals stationair
hydamo.laterals.read_gpkg_layer(gpkg_file, layer_name='lateraleknoop')
hydamo.laterals_gdf=hydamo.laterals
hydamo.laterals=ExtendedGeoDataFrame(geotype=Point)
hydamo.laterals.set_data(hydamo.laterals_gdf, index_col='globalid')
hydamo.laterals.snap_to_branch(hydamo.branches, snap_method='overal', maxdist=1000)
hydamo.laterals.dropna(axis=0, inplace=True, subset=["branch_offset"])

# only first 10 branches/laterals
hydamo.branches = hydamo.branches.iloc[:10]
hydamo.laterals = hydamo.laterals.iloc[:10]

fm = FMModel()
# Set start and stop time
fm.time.refdate = 20160601
fm.time.tstop = 2 * 3600 * 24

mesh.mesh1d_add_branches_from_gdf(
    fm.geometry.netfile.network,
    branches=hydamo.branches,
    branch_name_col="code",
    node_distance=20,
    max_dist_to_struc=None,
    structures=None,
)

print('Adding laterals')
hydamo.laterals.dropna(subset = 'qw_l_s_ha', inplace=True)
lateral_discharges = (hydamo.laterals["qw_l_s_ha"]*hydamo.laterals["opp_ondiep"]/10000)/1000 #van l/s/ha naar m3/s
lateral_discharges.index = hydamo.laterals.code
lateral_discharges[lateral_discharges.isna()] = 0.0
hydamo.external_forcings.convert.laterals(hydamo.laterals, lateral_discharges=lateral_discharges, rr_boundaries=None)

print('Converting to ExtModel object')
models = Df2HydrolibModel(hydamo)

extmodel = ExtModel()

extmodel.lateral = models.laterals_ext # hier wordt alleen de 1e lateraaltoegevoegd
fm.external_forcing.extforcefilenew = extmodel

lateral_ids = [x.id for x in extmodel.lateral]
lateral0_forcing_names = [x.name for x in extmodel.lateral[0].discharge.forcing]
print(lateral_ids)
print(lateral0_forcing_names)
```

This prints the following:
```
['lat_GE1_4331', 'lat_ZL32_3099', 'lat_BS86_1421', 'lat_KD25_6467', 'lat_ZL32_3098', 'lat_DO1.2_2267', 'lat_ZL16_929', 'lat_DL32_4880', 'lat_KD25_6469', 'lat_KS1_3511']
['lat_GE1_4331', 'lat_ZL32_3099', 'lat_BS86_1421', 'lat_KD25_6467', 'lat_ZL32_3098', 'lat_DO1.2_2267', 'lat_ZL16_929', 'lat_DL32_4880', 'lat_KD25_6469', 'lat_KS1_3511']
```

This is surprising: I would expect that there are n (10 in this case) lateral_ids. However, I do not expect that for each lateral, there are n (10) forcings added with the same names as the laterals. What I expect is that somewhere in dhydamo a loop is duplicated, resulting not only in 6000 laterals, but with 6000 forcings for each lateral also. In this case it makes sense that the bc file is written again and again and also that this takes quite some time.

@RuudHurkmans could you give your view on this?

**Comment by veenstrajelmer** [comment]
I did some additional research and it seems that the forcings are shared over all laterals. When replacing the forcing of the last lateral with an empty list, the forcing of the first lateral is an empty list also:
```python
extmodel.lateral[-1].discharge.forcing = []
print(extmodel.lateral[0].discharge.forcing)
```
Prints:
```
[]
```

Therefore, with the current example is not possible to assign each nth forcing to each nth lateral at this moment. This might be a bug. It might even be a bug it is possible to assign multiple forcings to one lateral also. It might also be a bug in dhydamo however (appending to forcing in the loop instead of assigning only one forcing), so please check this.

Either way, to avoid the duplicated information (workaround), I would say the list of laterals can be replaced with a single `Lateral` object (with +-6000 forcings) like this:
```python
extmodel.lateral = [extmodel.lateral[0]]
```

Could you check this?

In the meantime I will check internally whether there is something to be fixed in hydrolib-core regarding laterals.
